/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ListOfBooksListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheListOfBooksList.iSeeThisPage();
        });


        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheListOfBooksList.onTable().iCheckColumns(undefined, {"ID":{"header":"{i18n>Title}"},"author":{"header":"{i18n>Author}"},"genre/name":{"header":"genre/name"},"price":{"header":"{i18n>Price}"},"currency/symbol":{"header":"currency/symbol"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            Then.onTheListOfBooksList.onTable().iCheckRows();

            When.onTheListOfBooksList.onTable().iPressRow(0);
            Then.onTheListOfBooksObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});