/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ListOfOrdersListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheListOfOrdersList.iSeeThisPage();
        });


        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheListOfOrdersList.onTable().iCheckColumns(undefined, {"orderNo":{"header":"{i18n>OrderNo}"},"orderDate":{"header":"{i18n>OrderDate}"},"customer/name":{"header":"{i18n>Customer}"},"status":{"header":"{i18n>Status}"},"grossAmount":{"header":"{i18n>GrossAmount}"},"currency/code":{"header":"currency/code"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data

            Then.onTheListOfOrdersList.onTable().iCheckRows();

            When.onTheListOfOrdersList.onTable().iPressRow(0);
            Then.onTheListOfOrdersObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});
