/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ListOfOrdersObjectPageObjectPage journey");

        opaTest("Navigate to ListOfOrdersObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheListOfOrdersList.onTable().iCheckRows();
            When.onTheListOfOrdersList.onTable().iPressRow(0);

            Then.onTheListOfOrdersObjectPage.iSeeThisPage();
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheListOfOrdersObjectPage.iCheckSection({ section: "FieldGroup::General" });
            Then.onTheListOfOrdersObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "orderNo" });
            Then.onTheListOfOrdersObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "status" });
       });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});
