/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ListOfBooksObjectPageObjectPage journey");

        opaTest("Navigate to ListOfBooksObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheListOfBooksList.onTable().iCheckRows();
            When.onTheListOfBooksList.onTable().iPressRow(0);

            Then.onTheListOfBooksObjectPage.iSeeThisPage();
        });

        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onTheListOfBooksObjectPage.onHeader().iCheckHeaderFacet({ facetId: "FieldGroup::Descr" });
            Then.onTheListOfBooksObjectPage.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "FieldGroup::Descr",
                field: "descr",
                targetAnnotation: ""
            });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheListOfBooksObjectPage.iCheckSection({ section: "FieldGroup::Price" });
            Then.onTheListOfBooksObjectPage.onForm({ section: "FieldGroup::Price" }).iCheckField({ property: "price" });
            Then.onTheListOfBooksObjectPage.onForm({ section: "FieldGroup::Price" }).iCheckField({ property: "currency/symbol" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});